# Generated by Django 4.0.6 on 2022-07-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='body',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='updated',
        ),
        migrations.AddField(
            model_name='player',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
