# Generated by Django 4.0.6 on 2022-09-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_body_player_name_remove_player_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
