# Generated by Django 4.0.6 on 2022-09-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_card_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='card_img',
        ),
        migrations.AddField(
            model_name='player',
            name='img_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
